TARGET = spsc_test_shadow_heur
include(test_runner_common.pri)

DEFINES += \
    SPSC_TEST_EXPECTED_VARIANT_NAME=\\\"shadow_heur\\\" \
    SPSC_TEST_EXPECTED_ENABLE_SHADOW_INDICES=1 \
    SPSC_TEST_EXPECTED_SHADOW_ALLOW_32BIT=1 \
    SPSC_TEST_EXPECTED_SHADOW_REFRESH_HEURISTIC=1 \
    SPSC_ENABLE_SHADOW_INDICES=1 \
    SPSC_SHADOW_ALLOW_32BIT=1 \
    SPSC_SHADOW_REFRESH_HEURISTIC=1
