TARGET = spsc_test_shadow_off
include(test_runner_common.pri)

DEFINES += \
    SPSC_TEST_EXPECTED_VARIANT_NAME=\\\"shadow_off\\\" \
    SPSC_TEST_EXPECTED_ENABLE_SHADOW_INDICES=0 \
    SPSC_TEST_EXPECTED_SHADOW_ALLOW_32BIT=0 \
    SPSC_TEST_EXPECTED_SHADOW_REFRESH_HEURISTIC=0 \
    SPSC_ENABLE_SHADOW_INDICES=0 \
    SPSC_SHADOW_ALLOW_32BIT=0 \
    SPSC_SHADOW_REFRESH_HEURISTIC=0
