TARGET = spsc_test_cxx20_span

SPSC_TEST_CXX_STANDARD = c++20
SPSC_TEST_SPAN_ENABLED = 1

include(test_runner_common.pri)

DEFINES += \
    SPSC_TEST_EXPECTED_VARIANT_NAME=\\\"cxx20_span\\\" \
    SPSC_TEST_EXPECTED_ENABLE_SHADOW_INDICES=0 \
    SPSC_TEST_EXPECTED_SHADOW_ALLOW_32BIT=0 \
    SPSC_TEST_EXPECTED_SHADOW_REFRESH_HEURISTIC=0 \
    SPSC_TEST_EXPECTED_HAS_SPAN=1 \
    SPSC_ENABLE_SHADOW_INDICES=0 \
    SPSC_SHADOW_ALLOW_32BIT=0 \
    SPSC_SHADOW_REFRESH_HEURISTIC=0
